apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "databricks-ovh-provider.fullname" . }}
  labels:
    {{- include "databricks-ovh-provider.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "databricks-ovh-provider.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "databricks-ovh-provider.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "databricks-ovh-provider.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: OVH_ENDPOINT
              value: {{ .Values.config.ovh.endpoint | quote }}
            - name: OVH_APPLICATION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "databricks-ovh-provider.fullname" . }}-config
                  key: ovh-application-key
            - name: OVH_APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "databricks-ovh-provider.fullname" . }}-config
                  key: ovh-application-secret
            - name: OVH_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "databricks-ovh-provider.fullname" . }}-config
                  key: ovh-consumer-key
            - name: OVH_PROJECT_ID
              value: {{ .Values.config.ovh.projectId | quote }}
            - name: DATABRICKS_ACCOUNT_ID
              value: {{ .Values.config.databricks.accountId | quote }}
            - name: DATABRICKS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "databricks-ovh-provider.fullname" . }}-config
                  key: databricks-username
            - name: DATABRICKS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "databricks-ovh-provider.fullname" . }}-config
                  key: databricks-password
            - name: DATABRICKS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "databricks-ovh-provider.fullname" . }}-config
                  key: databricks-token
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
