apiVersion: v1
kind: Secret
metadata:
  name: {{ include "databricks-ovh-provider.fullname" . }}-config
  labels:
    {{- include "databricks-ovh-provider.labels" . | nindent 4 }}
type: Opaque
data:
  ovh-application-key: {{ .Values.config.ovh.applicationKey | b64enc | quote }}
  ovh-application-secret: {{ .Values.config.ovh.applicationSecret | b64enc | quote }}
  ovh-consumer-key: {{ .Values.config.ovh.consumerKey | b64enc | quote }}
  databricks-username: {{ .Values.config.databricks.username | b64enc | quote }}
  databricks-password: {{ .Values.config.databricks.password | b64enc | quote }}
  databricks-token: {{ .Values.config.databricks.token | b64enc | quote }}
